steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: wait-previous
    entrypoint: bash
    args:
      - '-c'
      - |
        REGION="$${_REGION:-asia-east1}"
        CURRENT_TRIGGER="$${_TRIGGER_NAME}"
        CURRENT_BUILD_ID="${BUILD_ID}"

        echo "🔎 Checking for previous builds of trigger $${CURRENT_TRIGGER}..."
        echo "Current Build ID: $${CURRENT_BUILD_ID}"

        # Get start time of current build
        CURRENT_START=$$(gcloud builds describe $${CURRENT_BUILD_ID} --region=$${REGION} --format="value(createTime)")
        echo "Current build start time: $${CURRENT_START}"

        # List all running/queued builds for this trigger, sorted by createTime ascending
        PREV_BUILDS=$$(gcloud builds list --region=$${REGION} \
          --filter="status:(WORKING OR QUEUED) AND substitutions._TRIGGER_NAME=$${CURRENT_TRIGGER}" \
          --sort-by="createTime" \
          --format="value(id,createTime)")

        # Convert to array
        mapfile -t BUILDS_ARRAY <<< "$${PREV_BUILDS}"

        wait_for_build() {
          local BUILD_ID=$$1
          while true; do
            STATUS=$$(gcloud builds describe $$BUILD_ID --region=$${REGION} --format="value(status)")
            if [[ "$${STATUS}" == "SUCCESS" || "$${STATUS}" == "FAILURE" || "$${STATUS}" == "CANCELLED" ]]; then
              echo "Build $$BUILD_ID finished with $$STATUS"
              break
            fi
            echo "⏳ Build $$BUILD_ID still running, waiting 15s..."
            sleep 15
          done
        }

        for BUILD_INFO in "$${BUILDS_ARRAY[@]}"; do
          BUILD_ID=$$(echo $$BUILD_INFO | awk '{print $$1}')
          BUILD_START=$$(echo $$BUILD_INFO | awk '{print $$2}')

          # Skip if it's the current build or started after current build
          if [[ "$$BUILD_ID" == "$${CURRENT_BUILD_ID}" || "$$BUILD_START" > "$${CURRENT_START}" ]]; then
            continue
          fi

          echo "⏳ Waiting for earlier build $$BUILD_ID started at $$BUILD_START..."
          wait_for_build $$BUILD_ID
        done

        echo "✅ Current build is the earliest or all previous builds finished → proceeding."



timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TRIGGER_NAME: trigger-2
  _GCS_BUCKET: inosuke-wasi-wasi
  _API_NAME: api2
  _GITHUB_REPO: 20481A04K2/repo22
